### PR TITLE
add identation wrapping - client side (#25)

### PR DESCRIPTION
**Pull request by nat236919**
**Related Issue:**:

- #25 

**Fixes and Features:**

- [x] Add indentation for a conversational long text  (client-side)
- [x] Add utility as helper
- [x] Add type hints

**Tests**

- [x] Windows10's console -> it seemed to work properly

**Screenshot**

- client

image

- server

image

**Additional Explanation**

Using **textwrap** lib allows conversational texts to be presented properly since it breaks texts word by word.

### CODE REVIEW

**Review by t0xic0der — CHANGES_REQUESTED** [review]
This does not seem to work here.

image

**Comment by nat236919** [comment]
@t0xic0der It now only works when receive messages. Can you confirm with two or more clients on the same chatroom?

**Comment by t0xic0der** [comment]
Yes, you are right. It only works while receiving messages.
image

There are certain discrepancies that I would like for you to note.

- I think you might have hardcoded the length of the string due to which certain smaller terminal sizes don't really look pleasing and the ones bigger in size are not completely utilized.
- Also, please restrict the time to the first line only, like you restricted the username. Repeating it does not make much sense.

**Comment by nat236919** [comment]
Temporarily closed for revision

**Comment by nat236919** [comment]
@t0xic0der I have just added the first revision, please have a look.
@melsaa I moved your code to the utilities and modified a part of it, hope you don't mind.

**Comment by melsaa** [comment]
> @melsaa I moved your code to the utilities and modified a part of it, hope you don't mind.

Sure, the modification looks great to me. Thanks!

**Comment by t0xic0der** [comment]
Let me take a look at it.

**Review by t0xic0der — CHANGES_REQUESTED** [review]
Note the following points

- The indentation is still messed up at the sender's side but seems completely composed on the receiver's end.
- There's an extra line formed after the composed message is displayed at the receiver's end.

Here's one hint which you might make use of. https://python-prompt-toolkit.readthedocs.io/en/master/pages/asking_for_input.html#multiline-input.

image

**Comment by nat236919** [comment]
> Note the following points
> 
> * The indentation is still messed up at the sender's side but seems completely composed on the receiver's end.
> * There's an extra line formed after the composed message is displayed at the receiver's end.
> 
> Here's one hint which you might make use of. https://python-prompt-toolkit.readthedocs.io/en/master/pages/asking_for_input.html#multiline-input.

@t0xic0der 
* There's an extra line formed after the composed message is displayed at the receiver's end. (**fixed:** https://github.com/t0xic0der/sanctuary-zero/pull/43/commits/4872a96a33861d5680f4b9ecd458eba3c5dba9ba)
* The indentation is still messed up at the sender's side but seems completely composed on the receiver's end

By using multiline=True will cause a side effect, a user cannot press enter to send an input. A user needs to press **Meta+Enter** or **ESC + Enter** to send.

That's why I haven't included it, I'm not so sure if there's any other solution.

**Comment by nat236919** [comment]
@t0xic0der Everything should work properly now

image

**Review by t0xic0der — APPROVED** [review]
This is `m3x1c0`'s end.

image

This is `t0xic0der`'s end.

image

It looks awesome. Thank you.

(It does become distorted once the window is resized but dont' worry, we don't really need that kind of polish right now)

**Pull request merged**
