### PR TITLE
Returning chatroom users-list on /list command

### PR DESCRIPTION
**Pull request by Vivek-blip**

### CODE REVIEW

**Comment by t0xic0der** [comment]
Let me quickly assign #57 to you before I get into reviewing your code. :+1:

**Comment by nat236919** [comment]
@t0xic0der If I may point something out, this merge will undo some previous works.

we have a number of devs working in the same files. I think it is practical that forked repos be updated before merging in order to be even with the original repo.

**Comment by Vivek-blip** [comment]
> @t0xic0der @Vivek-blip If I may point something out, this merge will undo some previous works.
> 
> we have a number of devs working in the same files. I think it is practical that forked repos be updated before merging in order to be even with the original repo.

@nat236919 I had updated my fork before making this pr. It was in sync with `toxicoder:master` until this pr was made.
Now though its outdated i agree 😅

**Comment by t0xic0der** [comment]
@nat236919 Yep. Checked the PR and found a lot of things absent.

@Vivek-blip Please rebase your fork to match the latest commit made to the master and then, make your changes.

(NB. The dirtiest and the fastest way of doing so is by getting rid of your fork and then, forking the updated repository again to add your changes)

**Pull request closed without merging**
