### PR TITLE
Issue-19: Add Executable for Linux Client

### PR DESCRIPTION
**Pull request by vinmay**
Issue #19

### CODE REVIEW

**Comment by t0xic0der** [comment]
Cool. Let me get into reviewing it.

**Comment by t0xic0der** [comment]
@vinmay You would want to rebase to the most recent `master`. I do not see the remaining Windows 10 executables here which means they must have been undone with this PR of yours.

**Comment by vinmay** [comment]
@t0xic0der It is the latest master. The dist folder is in the .gitignore, thats why you would not see it. I had to add a -f flag to push this exec on GitHub. I assumed that was intentional.

**Comment by vinmay** [comment]
@t0xic0der Let me know if we want to change this. I can update the .gitignore as well if that is what is expected.

**Comment by vinmay** [comment]
@t0xic0der Found the issue at my end and updated the exec !!!

**Comment by t0xic0der** [comment]
> The dist folder is in the .gitignore, thats why you would not see it. I had to add a -f flag to push this exec on GitHub. I assumed that was intentional.

I know. The contents of the `dist` folder would not have made across if it were not for the flag.

> I can update the .gitignore as well if that is what is expected.

Don't. Adding executables is an exception, rather than a norm so we would not want to change the `.gitignore` file to facilitate such small changes.

> Found the issue at my end and updated the exec !!!

Glad to know. Heading in to review now.

**Review by t0xic0der — APPROVED** [review]
Looks good to me. Approving.

**Comment by t0xic0der** [comment]
Now that I have approved the pull request, @shivangswain please go ahead and merge it.

**Pull request merged**
